version: "3.9"
services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wp-volume:/var/www/
    environment:
      WP_NAME: ${WP_NAME}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASS: ${WP_ADMIN_PASS}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_USER_PASS: ${WP_USER_PASS}
      WP_USER: ${WP_USER}
      DOMAIN_NAME: ${DOMAINE_NAME}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    ports:
      - "3306:3306"
    environment:
      DB_ROOT: ${DB_ROOT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - inception
    restart: always

volumes:

# This is the volume for the wordpress and NGINX containers
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

# This is the volume for the MariaDB container
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
  inception:
    driver: bridge